feat(impl): [#518] Cucumber test step definitions for Policy Store API
eclipse-tractusx/item-relationship-service pull request #584
Opened 2024-05-02 17:55 UTC by dsmf

Story: https://github.com/eclipse-tractusx/item-relationship-service/issues/518

## Description

Implementation of Policy Store API Cucumber test step definitions including:
- Split up the E2E step definition classes into two classes (one for each API: job API and policy API).
- Move some code to helper classes.
- Configure RESTAssured request / response logging centrally (for better debugging and in order to see progress when github action runs).

The tests itself are not included because they are defined in XRAY. See comment in story: https://github.com/eclipse-tractusx/item-relationship-service/issues/518#issuecomment-2083989087 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-05-06 07:51 UTC, dsmf commented on irs-cucumber-tests/src/test/java/org/eclipse/tractusx/irs/cucumber/E2ETestHelperForPolicyStoreApi.java
> +    public record CreatePolicyRequest(OffsetDateTime validUntil, String businessPartnerNumber, JsonNode payload) {
@ds-ext-kmassalski This would add a lot of transitive dependencies which is not justifiable in view of the benefits.

2024-05-06 09:29 UTC, dsmf commented on irs-cucumber-tests/src/test/java/org/eclipse/tractusx/irs/cucumber/E2ETestHelperForPolicyStoreApi.java
> +    public static Map<String, ArrayList<LinkedHashMap<String, ?>>> fetchAllPoliciesSuccessfully(
Hi @ds-ext-kmassalski, the reason is that the controller returns a Map: `Map<String, List<PolicyResponse>>`. I think I tried it this way, but did not work. If you know a good way how to correctly map this to a business data type I'd appreciate. However another reason for avoiding the use of PolicyResponse is that we'd have to add irs-policy-store as a dependency introducing a lot of unnecessary transitive dependencies.

2024-05-07 13:18 UTC, ds-jhartmann requested changes

2024-05-07 13:27 UTC, dsmf commented on irs-cucumber-tests/src/test/java/org/eclipse/tractusx/irs/cucumber/E2ETestHelperForPolicyStoreApi.java
> +    public record CreatePolicyRequest(OffsetDateTime validUntil, String businessPartnerNumber, JsonNode payload) {
true, but the original classes are not in models, they are in irs-policy-store

2024-05-07 13:31 UTC, dsmf commented on CHANGELOG.md
> +- Cucumber test step definitions for Policy Store API (Happy Path) including some test helper utilities. #518
done

2024-05-07 13:36 UTC, ds-jhartmann commented on irs-cucumber-tests/src/test/java/org/eclipse/tractusx/irs/cucumber/E2ETestHelperForPolicyStoreApi.java
> +    public record CreatePolicyRequest(OffsetDateTime validUntil, String businessPartnerNumber, JsonNode payload) {
works for me

2024-05-07 13:47 UTC, ds-jhartmann approved these changes
LGTM

2024-05-07 13:48 UTC, merged