feat(impl): [#528] allow only BPNL
eclipse-tractusx/item-relationship-service pull request #597
Opened 2024-05-07 12:27 UTC by dsmf

## Description

- story: https://github.com/eclipse-tractusx/item-relationship-service/issues/528

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-05-13 09:00 UTC, ds-jhartmann requested changes

2024-05-13 09:35 UTC, ds-jhartmann commented
1 PMD violation https://github.com/eclipse-tractusx/item-relationship-service/actions/runs/9035341234/job/24829878885?pr=597#step:5:9503

2024-05-13 09:58 UTC, dsmf commented on irs-policy-store/src/main/java/org/eclipse/tractusx/irs/policystore/models/UpdatePolicyRequest.java
> +        @Future(message = "must be in future") //
the message is automatically prefixed with the field name by the framework:
![grafik](https://github.com/eclipse-tractusx/item-relationship-service/assets/19529362/bb62746f-08f4-4a5c-bf13-0991b2f2748d)

2024-05-13 10:23 UTC, dsmf commented on irs-policy-store/src/main/java/org/eclipse/tractusx/irs/policystore/models/CreatePolicyRequest.java
> +        @Future(message = "must be in future") //
the message is automatically prefixed with the field name by the framework:
![grafik](https://github.com/eclipse-tractusx/item-relationship-service/assets/19529362/bb62746f-08f4-4a5c-bf13-0991b2f2748d)

2024-05-14 07:54 UTC, ds-jhartmann approved these changes
LGTM

2024-05-14 07:58 UTC, merged