feature: eclipse-tractusx/traceability-foss#639 add catch clause
eclipse-tractusx/item-relationship-service pull request #698
Opened 2024-06-17 09:12 UTC by ds-lcapellino

## Description

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-07-09 14:46 UTC, dsmf requested changes

2024-07-10 09:16 UTC, dsmf commented on irs-api/src/main/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/RelationshipDelegate.java
> +        } catch (final UsagePolicyPermissionException | UsagePolicyExpiredException e) {
```suggestion
        } catch (final PolicyException e) {
```

now both have the interface so you can just catch on the interface

2024-07-10 11:31 UTC, dsmf approved these changes

2024-07-10 12:10 UTC, ds-jhartmann approved these changes
LGTM

2024-07-10 12:10 UTC, merged